### ISSUE TITLE
Resource

### ISSUE THREAD

**Issue by warzes** [yhkim8912/GameEngine_OpenGL#1]
where to get the folder with the resources of the engine?

**Comment by lasyowl** [comment]
Sorry for replying late. Unfortunately, the paths of resource folders are hard-coded. I have a plan to renew the engine in close future, so if you are interested in my work, keep your eye on!🙄 By the way, the hard-coded resource path are (root of project folder₩res₩...) for textures, and (d:₩3d models₩...) for 3d models.
